# Generated by Django 3.2 on 2023-05-31 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskLine',
        ),
    ]
